#  typos-cli configuration file
# https://github.com/crate-ci/typos#false-positives

[default]
extend-ignore-identifiers-re = [
]

[default.extend-identifiers]

[default.extend-words]
aer = "aer"
AER = "AER"
atend = "atend"
bck="bck"
clos = "clos"
decorder="decorder"
ECT = "ECT"
FILS = "FILS"
fpr = "fpr"
gam = "gam"
gost = "gost"
Hashi = "Hashi"
iif = "iif"
importas="importas"
ist = "ist"
lits = "lits"
nd = "nd"
nexting = "nexting"
OCE = "OCE"
oif = "oif"
opf = "opf"
parm = "parm"
parms = "parms"
pn = "pn"
reord = "reord"
rto = "rto"
ser = "ser"
siz = "siz"
sme = "sme"
tha = "tha"
thr = "thr"
tio = "tio"
typ = "typ"
UE = "UE"
unmarshaling = "unmarshaling"
wrk = "wrk"
